"""µC teaching frontend for parsing and lowering into canonical µIR."""

from .ast import (
    ArrayLiteral,
    ArrayAssign,
    ArrayRef,
    Assign,
    BinaryExpr,
    Block,
    BoolLiteral,
    CallExpr,
    Decl,
    Expr,
    ExprStmt,
    For,
    FunctionDef,
    If,
    IntegerLiteral,
    Param,
    Program,
    Return,
    StringLiteral,
    Stmt,
    TypeRef,
    UnaryExpr,
    VarRef,
)
from .lexer import LexError, Token, tokenize
from .lower import lower_function, lower_program, lower_source_to_uir
from .parser import ParseError, parse_program
from .sema import FunctionInfo, ProgramInfo, SemanticError, analyze_function, analyze_program, lowerable_type
from .ssa import UIRConstructionError, to_uir_function, to_uir_module

__all__ = [
    "ArrayAssign",
    "ArrayLiteral",
    "ArrayRef",
    "Assign",
    "BinaryExpr",
    "Block",
    "BoolLiteral",
    "CallExpr",
    "Decl",
    "Expr",
    "ExprStmt",
    "For",
    "FunctionDef",
    "FunctionInfo",
    "If",
    "IntegerLiteral",
    "LexError",
    "Param",
    "ParseError",
    "Program",
    "ProgramInfo",
    "Return",
    "SemanticError",
    "StringLiteral",
    "Stmt",
    "Token",
    "TypeRef",
    "UnaryExpr",
    "VarRef",
    "analyze_function",
    "analyze_program",
    "lower_function",
    "lower_program",
    "lower_source_to_uir",
    "lowerable_type",
    "parse_program",
    "tokenize",
    "to_uir_function",
    "to_uir_module",
    "UIRConstructionError",
]
