name: uhls ci

on:
  push:
    paths-ignore:
      - "doc/**"
      - "README*"
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "README*"
    branches:
      - master
  workflow_dispatch: {}

jobs:
  test-flows:
    name: run uhls unit tests, examples, flows, ...
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - {name: "ubuntu", version: "latest"}
        container:
          - {name: "tumeda/eda-osic-tools", version: "latest-default"}

    container: ${{ matrix.container.name }}:${{ matrix.container.version }}-${{ matrix.os.name }}-${{ matrix.os.version }}

    steps:
      - name: install git on container
        run: |
          apt update && apt install -y git

      - name: Clone repo
        uses: actions/checkout@v4
        with:
          path: uhls_src
          submodules: recursive

      - name: load container env
        run: |
          . /eda-osic-tools/env.sh /eda-osic-tools/.env
          {
            echo "VENV_ROOT=${VENV_ROOT}"
            echo "YOSYS_EXE=${YOSYS_EXE}"
            echo "ORFS_ROOT=${ORFS_ROOT}"
            echo "PDK_ROOT=${PDK_ROOT}"
            echo "IHP130_PDK_ROOT=${IHP130_PDK_ROOT}"
          } >> "${GITHUB_ENV}"

      - name: run uhls unit tests
        working-directory: uhls_src
        run: |
          . "${VENV_ROOT}/bin/activate"
          python3 -m pip install -r requirements.txt
          PYTHONPATH=src python3 -m unittest discover -s test -v

      - name: build uhls examples
        working-directory: uhls_src
        run: |
          . "${VENV_ROOT}/bin/activate"
          python3 -m pip install -r requirements.txt
          make -C examples STEM=dot4_relu
